services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:3000"
    environment:
      - OPENAI_API_BASE_URL=${OPENAI_API_BASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DEEPSEEK_OPENAI_BASE_URL=${DEEPSEEK_OPENAI_BASE_URL}
      - DEEPSEEK_OPENAI_KEY=${DEEPSEEK_OPENAI_KEY}
      - PB_SUPERADMIN_TOKEN=${PB_SUPERADMIN_TOKEN}
      - PB_URL=${PB_URL}
      - PB_SUPERADMIN_USER=${PB_SUPERADMIN_USER}
      - PB_SUPERUSER_ADMIN_PASSWORD=${PB_SUPERUSER_ADMIN_PASSWORD}
      - PORT=${PORT}